### PR TITLE
 initial avatars and content images support

### PR DESCRIPTION
**Pull request by a-andreyev**

### CODE REVIEW

**Comment by Quiark** [comment]
I'm having some crash on exit, happens each time. macOS latest

```
1  ___lldb_unnamed_symbol3646$$QtQml                                0x1012c78e1    
2  ___lldb_unnamed_symbol3641$$QtQml                                0x1012c7631    
3  QHashData::free_helper(void ( *)(QHashData::Node *))             0x100c29f59    
4  QQmlEnginePrivate::~QQmlEnginePrivate()                          0x1012bd422    
5  QQmlEnginePrivate::~QQmlEnginePrivate()                          0x1012bd53e    
6  QObject::~QObject()                                              0x100dbc1f8    
7  QQmlEngine::~QQmlEngine()                                        0x1012bedd8    
8  QQmlEngine::~QQmlEngine()                                        0x1012bee2e    
9  QObjectPrivate::deleteChildren()                                 0x100dbc3cb    
10 QObject::~QObject()                                              0x100dbc1c7    
11 QWindow::~QWindow()                                              0x1006eab2e    
12 QQuickWindow::~QQuickWindow()                                    0x10042d685    
13 main                                                 main.cpp 69 0x1000b1fee    
14 start                                                            0x7fff5052b015 
15 start                                                            0x7fff5052b015 
```

**Comment by Quiark** [comment]
But it's probably not specific to this pull request

**Comment by Quiark** [comment]
Or it is. It goes away if I comment out creating the image provider in `main.cpp`.

**Comment by KitsuneRal** [comment]
You shouldn't put the image provider in a `QScopedPointer`; the QML engine will clean it up. Actually what happens is that the QML engine comes late to the cleanup party and tries to dispose of an already deleted object. Just replace `QScopedPointer` with a raw pointer, and things should be fine.

**Pull request merged**
